name: flutter_sticker_maker
description: Flutter plugin to create stickers from images using iOS Vision/CoreImage and ONNX (below iOS 17.0 and Android).
version: 0.2.0
repository: https://github.com/asionbo/flutter-sticker-maker
# publish_to: https://pub.dartlang.org

environment:
  sdk: '^3.7.0'
  flutter: ">=3.24.0"

flutter:
  assets:
    - assets/
  plugin:
    platforms:
      ios:
        pluginClass: FlutterStickerMakerPlugin
      android:
        package: com.asionbo.flutter_sticker_maker
        pluginClass: FlutterStickerMakerPlugin
dependencies:
  flutter:
    sdk: flutter
  flutter_onnxruntime: ^1.5.2
  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: ^11.0.0